config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"


  resources :customers do
    collection do
      get 'alphabetized'
      get 'missing_email'
    end
  end

   root to: "customers#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_one_attached :image

  validates :FullName, presence: true

  validates :EmailAddress, uniqueness: true, allow_blank: true
  def self.ransackable_attributes(auth_object = nil)
    ["EmailAddress", "FullName", "Notes", "PhoneNumber", "created_at", "id", "updated_at"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

    def index
      @customers = Customer.all
    end

    def alphabetized
      @customers = Customer.order(:FullName)
    end

    def missing_email
      @customers = Customer.where(EmailAddress: [nil, ''])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<div class="column is-one-third">
<% if customer.image.present? %>
  <div class="card-image">
    <figure class="image is-4by3">
      <%= image_tag customer.image %>
    </figure>
  </div>
<% end %>
  <div class="card customer">
    <div class="card-content">
    <ul>
      <li>
        <strong>Full Name:</strong> <%= customer.FullName %>
      </li>
      <li>
        <strong>Email Address:</strong> <%= customer.EmailAddress%>
      </li>
      <li>
        <strong>Phone Number:</strong> <%= customer.PhoneNumber %>
      </li>
      <li>
        <strong>Notes:</strong> <%= customer.Notes %>
      </li>
    </ul>
    </div>
  </div>
</div>

app/views/customers/alphabetized.html.erb
<h3 class="title is-4">Customers Ordered Alphabetically</h3>

<div>
  <%= link_to 'All Customers', root_path %>
  <%= link_to 'Customers Missing Email', missing_email_customers_path %> |
</div>

<% @customers.each do |customer| %>
  <%= render partial: "customer", locals: { customer: customer } %>
<% end %>

app/views/customers/index.html.erb
<h3 class="title is-4">All Customers</h3>

<div>
  <%= link_to 'Customers Missing Email', missing_email_customers_path %> |
  <%= link_to 'Customers Alphabetized', alphabetized_customers_path %>
</div>

<% @customers.each do |customer| %>
  <%= render partial: "customer", locals: { customer: customer } %>
<% end %>

app/views/customers/missing_email.html.erb
<h3 class="title is-4">Customers Missing Email Addresses</h3>

<div>
  <%= link_to 'All Customers', root_path %> |
  <%= link_to 'Customers Alphabetized', alphabetized_customers_path %>
</div>

<% @customers.each do |customer| %>
  <%= render partial: "customer", locals: { customer: customer } %>
<% end %>

app/views/customers/missingemail.html.erb
<h3 class="title is-4">Customers Missing Email Addresses</h3>


<% @customers.each do |customer| %>
  <%= render partial: "customer", locals: { customer: customer } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Customer Relation Manager" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
  </head>

  <body>
    <section class="section">
      <h1 class="title"><%= link_to 'Customers', root_path %></h1>
      <h2 class="subtitle">All Customers</h2>
    </section>
    <section class="section">
      <%= yield %>
    </section>
  </body>
</html>